// List of top universities in India
const universities = [
    // IITs (Indian Institutes of Technology)
    'IIT Bombay',
    'IIT Delhi',
    'IIT Madras',
    'IIT Kanpur',
    'IIT Kharagpur',
    'IIT Roorkee',
    'IIT Guwahati',
    'IIT Hyderabad',
    'IIT Indore',
    'IIT BHU (Varanasi)',
    'IIT Ropar',
    'IIT Bhubaneswar',
    'IIT Gandhinagar',
    'IIT Jodhpur',
    'IIT Patna',
    'IIT Mandi',
    'IIT Palakkad',
    'IIT Tirupati',
    'IIT Dhanbad',
    'IIT Jammu',
    'IIT Dharwad',
    'IIT Goa',
    'IIT Bhilai',
    
    // NITs (National Institutes of Technology)
    'NIT Trichy',
    'NIT Surathkal (Karnataka)',
    'NIT Warangal',
    'NIT Calicut',
    'NIT Rourkela',
    'NIT Durgapur',
    'NIT Jaipur',
    'NIT Kurukshetra',
    'NIT Silchar',
    'NIT Allahabad',
    'NIT Bhopal',
    'NIT Nagpur',
    'NIT Surat',
    'NIT Hamirpur',
    'NIT Jalandhar',
    'NIT Raipur',
    'NIT Agartala',
    'NIT Patna',
    'NIT Meghalaya',
    'NIT Manipur',
    
    // IIITs (Indian Institutes of Information Technology)
    'IIIT Hyderabad',
    'IIIT Bangalore',
    'IIIT Delhi',
    'IIIT Allahabad',
    'IIIT Gwalior',
    'IIIT Jabalpur',
    'IIIT Kota',
    'IIIT Vadodara',
    'IIIT Nagpur',
    'IIIT Pune',
    
    // IIMs (Indian Institutes of Management)
    'IIM Ahmedabad',
    'IIM Bangalore',
    'IIM Calcutta',
    'IIM Lucknow',
    'IIM Kozhikode',
    'IIM Indore',
    'IIM Shillong',
    'IIM Rohtak',
    'IIM Ranchi',
    'IIM Raipur',
    'IIM Tiruchirappalli',
    'IIM Udaipur',
    'IIM Kashipur',
    'IIM Amritsar',
    'IIM Bodh Gaya',
    'IIM Sambalpur',
    'IIM Sirmaur',
    'IIM Nagpur',
    'IIM Visakhapatnam',
    'IIM Jammu',
    
    // Other Top Universities
    'Delhi University',
    'Jawaharlal Nehru University (JNU)',
    'University of Mumbai',
    'Anna University',
    'University of Calcutta',
    'Banaras Hindu University (BHU)',
    'Aligarh Muslim University (AMU)',
    'University of Hyderabad',
    'Jadavpur University',
    'Savitribai Phule Pune University',
    'University of Madras',
    'Jamia Millia Islamia',
    'Osmania University',
    'Andhra University',
    'University of Kerala',
    
    // Deemed Universities
    'BITS Pilani',
    'Vellore Institute of Technology (VIT)',
    'Birla Institute of Technology (BIT Mesra)',
    'Manipal Academy of Higher Education',
    'Thapar Institute of Engineering and Technology',
    'SRM Institute of Science and Technology',
    'Amity University',
    'Lovely Professional University (LPU)',
    'Kalinga Institute of Industrial Technology (KIIT)',
    'Symbiosis International University',
    'SASTRA University',
    'JSS Academy of Higher Education',
    'Shiv Nadar University',
    'OP Jindal Global University'
];

module.exports = universities;
